#+SETUPFILE: setup.org
#+TITLE: How to setup proxy at atos
#+AUTHOR: Eric
* About
- Atos is using proxy that requires authentication. 
- Many programs can use regular proxy, but can't use proxy requiring authentication.
- Cntlm is the solution bcs it can handle the authentication.
- It will create a new proxy server on localhost that programs can use.
- You only need to start Cntlm server and change program's proxy settings into Cntlm server.
* Install cntlm
Can download [[https://sourceforge.net/projects/cntlm/files/][here]]
* Modify config file
Modify C:\Program Files (x86)\Cntlm\cntlm.ini

Sample:
#+BEGIN_SRC
Username	a701480
#Domain		
Password	test
Proxy		proxy-sg.glb.my-it-solutions.net:84
NoProxy		localhost, 127.0.0.*, 10.*, 192.168.*
Listen		3128
#+END_SRC

Alphabets in username must be lowercase.
* Change Windows proxy settings
1. Go to Windows start, search for "Configure proxy server".
2. Go to LAN settings.
3. Uncheck "Use automatic configuration script.
4. Check "Use a proxy server for your LAN".
5. Put address 127.0.0.1, port 3128
* Start/stop cntlm
** Setup
If installation directory is located in C:\Program Files (x86)\Cntlm, to start cntlm, enter the following into cmd:
#+BEGIN_SRC
cd C:\Program Files (x86)\Cntlm
cntlm.exe -g
#+END_SRC
You can stop the process manually using Task Manager.
* Git settings
** Set proxy
Go to command line and type:
#+BEGIN_SRC
git config --global http.proxy http://127.0.0.1:3128
#+END_SRC
** Unset proxy
Go to command line and type:
#+BEGIN_SRC
git config --global --unset http.proxy
#+END_SRC
* Revert Windows proxy settings
May be needed before connecting to VPN (URA) when laptop is at home.
1. Go to Windows start, search for "Configure proxy server".
2. Go to LAN settings.
3. Check "Use automatic configuration script.
4. Uncheck "Use a proxy server for your LAN".
* NPM settings
** Set proxy
Go to command line and type:
#+BEGIN_SRC
npm config set proxy http://localhost:3128
npm config set https-proxy http://localhost:3128
npm config set strict-ssl false
npm config set registry "http://registry.npmjs.org/"
#+END_SRC
** Unset proxy
Go to command line and type:
#+BEGIN_SRC
npm config delete proxy
npm config delete https-proxy
npm config delete strict-ssl
npm config delete registry
#+END_SRC
